# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec0b7a51c2f20d707bfce7aae8d3cd9fd22ce45ff97f492d8a294b0625b4b4bc0394e3d4e52bfd6b8409aadf9861a8e3c05f3a3724080d0263135017fcdb3217

test:
  secret_key_base: 76d9fe18b786b0cd0ceea36729e35d2e34af252a70484cfe885a8030f4c6e820b399972497675973ae008ed4b305de8ad7e75a92203e491a840d8a6c390bef8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
